---

language: python
sudo: required
dist: trusty
python:
  - 2.7
before_install: # set up the machine
  - sudo apt-get update -qq
  - sudo apt-get install -qq ansible
install: # set up the environment
  - ansible-playbook ansible/dev.yml
script: # run the tests
  - python -m unittest discover -s test
