- name: install anaconda
  command: "{{item}} chdir={{ansible_env.HOME}} creates=miniconda"
  with_items:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -f 
  notify:
    - delete miniconda installer 

- name: source anaconda
  lineinfile: dest={{ansible_env.HOME}}/.bashrc regexp="^export.*miniconda2/bin" line="export PATH={{ansible_env.HOME}}/miniconda2/bin:$PATH"

- name: install common python packages
  command: "{{item}} chdir={{ansible_env.HOME}}"
  with_items:
    - miniconda2/bin/conda update --yes conda
    - miniconda2/bin/conda install --yes atlas numpy scipy matplotlib nose dateutil pandas flask supervisor tornado
