- name: deploy database service
  remote_user: ubuntu
  hosts: service

  pre_tasks:
    - name: install system packages
      sudo: yes
      apt: name={{item}} state=installed update_cache=yes cache_valid_time=3600
      with_items:
        - libpq-dev
        - liblzma-dev
        - libsnappy-dev
        - supervisor
        - gcc
        - g++
        - awscli
        - redis-server

    - name: start supervisord service and have it run during system startup
      sudo: yes
      service: name=supervisor state=started enabled=yes

  roles:
    - anaconda

  post_tasks:
    - name: install db service
      command: "{{ansible_env.HOME}}/miniconda2/bin/pip install crash_rate_aggregates --upgrade"

    - name: setup service
      sudo: yes
      template: src=templates/crash_rate_aggregates.conf.j2 dest=/etc/supervisor/conf.d/crash_rate_aggregates.conf

    - name: restart supervisor
      sudo: yes
      command: service supervisor restart

    - name: start service
      sudo: yes
      supervisorctl: name=crash_rate_aggregates_service state=started
